apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: valheim
  namespace: valheim
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
  hostnames:
    - "valheim.bergtobias.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: valheim-server
          port: 80
