apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: valheim-k8s
    repo: https://addyvan.github.io/valheim-k8s/
    version: 2.0.1  
    releaseName: valheim-server
    namespace: valheim
    valuesInline:
      worldName: myworld
      serverName: "Eggman's Valheim Server"
      password: "abbe123"
      storage:
        kind: hostvol
        hostvol:
          path: /data/valheim
      networking:
        serviceType: LoadBalancer
