apiVersion: v1
kind: Service
metadata:
  name: valheim-server-http
  namespace: valheim
spec:
  type: ClusterIP
  selector:
    app: valheim-server
  ports:
    - name: httpport
      port: 80
      targetPort: 80
      protocol: TCP
