apiVersion: v1
kind: Service
metadata:
  name: valheim-server-udp
  namespace: valheim
spec:
  type: LoadBalancer
  selector:
    app: valheim-server
  ports:
    - name: gameport
      port: 2456
      targetPort: 2456
      protocol: UDP
    - name: queryport
      port: 2457
      targetPort: 2457
      protocol: UDP
