apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-operator
    targetRevision: 2.7.1
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-stack
    targetRevision: 0.15.0
    helm:
      values: |
        eck-elasticsearch:
          enabled: true
          # You can add specific Elasticsearch resource config here, e.g.:
          # replicas: 1
          # version: "8.5.1"
        eck-kibana:
          enabled: true
        eck-agent:
          enabled: false
        eck-fleet-server:
          enabled: false
        eck-logstash:
          enabled: false
        eck-apm-server:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
