apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    chart: pihole
    targetRevision: 2.31.0
    helm:
      values: |
        dnsmasq:
          customDnsEntries:
            - address=/example.com/192.168.10.218

        persistentVolumeClaim:
          enabled: true

        serviceWeb:
          loadBalancerIP: 192.168.10.218
          type: LoadBalancer
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc-web

        serviceDns:
          mixedService: true
          nodePorts:
            tcp: 53
            udp: 53
          loadBalancerIP: 192.168.10.160
          type: LoadBalancer
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
