apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://mojo2600.github.io/pihole-kubernetes/'
      chart: pihole
      targetRevision: "2.31.0"
      helm:
        values: |
          password: "YourStrongPasswordHere"

          hostNetwork: true

          dns:
            enabled: true
            type: NodePort  # Ignored with hostNetwork, but required by chart

          service:
            type: ClusterIP

          persistence:
            enabled: true
            size: 5Gi

          cloudflared:
            enabled: false
    - repoURL: 'https://github.com/vercevo/platform-infra'
      path: cluster/pihole
      targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
