apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://mojo2600.github.io/pihole-kubernetes/' # Helm repo URL
      chart: pihole
      targetRevision: "2.31.0" # Pin to a specific chart version (check latest)
      helm:
        values: |
          pihole:
            password: "YourStrongPasswordHere"
          service:
            type: ClusterIP
          persistence:
            enabled: true
            size: 5Gi
          cloudflared:
            enabled: false
          dns:
            server: 0.0.0.0
    - repoURL: 'https://github.com/vercevo/platform-infra'
      path: cluster/pihole
      targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
