apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airbyte
  template:
    metadata:
      labels:
        app: airbyte
    spec:
      containers:
        - name: airbyte-server
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "500m"
          image: airbyte-server:latest
          env:
            - name: AIRBYTE_ROLE
              value: "server"
            - name: AIRBYTE_DB_HOST
              value: "airbyte-db"
            - name: AIRBYTE_DB_PORT
              value: "5432"
            - name: AIRBYTE_DB_USER
              value: "airbyte"
            - name: AIRBYTE_DB_PASSWORD
              value: "airbyte"
            - name: AIRBYTE_DB_DBNAME
              value: "airbyte"
          ports:
            - containerPort: 8000
