apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - http.yaml

helmCharts:
  - name: airbyte
    repo: https://airbytehq.github.io/helm-charts
    version: 1.7.1
    releaseName: airbyte
