apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: airbyte-route
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
  hostnames:
    - "airbyte.bergtobias.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: airbyte
          port: 8000
