apiVersion: v1
data:
  users.anonymous.enabled: 'true'
  admin.enabled: 'false'
  oidc.config: |
    name: GitHub
    issuer: https://github.com
    clientID: $argo-cd.oauth.clientId
    clientSecret: $argo-cd.oauth.clientSecret
    requestedIDTokenClaims:
      groups:
        essential: true
    requestedScopes:
      - openid
      - profile
      - email
      - read:org
kind: ConfigMap
metadata:
  name: argocd-cm
