apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.example.com
  admin.enabled: 'false'
  users.anonymous.enabled: 'false'
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $argo-cd.oauth.clientId
        clientSecret: $argo-cd.oauth.clientSecret
        orgs:
        - name: vercevo
