apiVersion: v1
data:
  application.resourceTrackingMethod: annotation
  admin.enabled: 'false'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'true'
  ga.trackingid: 'UA-105170809-6'
  url: https://argo-cd.bergtobias.com
  configManagementPlugins: |
    - name: flux
      generate:
        command: [sh, -c]
        args: ["argocd-flux-plugin . --path $GIT_PATH"]
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: Iv23liYT6ofML2cJDGIy
        clientSecret: $argocd-auth:dex.github.clientSecret
        orgs:
        - name: vercevo
          teams:
          - eggmans
kind: ConfigMap
metadata:
  name: argocd-cm
