apiVersion: v1
data:
  admin.enabled: "false"
  url: https://argocd.bergtobias.com
  kustomize.buildOptions: "--enable-helm"
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $clientId
        clientSecret: $clientSecret
        orgs:
        - name: vercevo
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
