apiVersion: v1
data:
  users.anonymous.enabled: 'true'
  admin.enabled: 'false'
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $argo-cd.oauth.clientId
        clientSecret: $argo-cd.oauth.clientSecret
        orgs:
        - name: vercevo
kind: ConfigMap
metadata:
  name: argocd-cm
