apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-lan-only
  namespace: observability
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: jaeger
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 192.168.0.0/16
