apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: jaeger-deny-all
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: jaeger-query
  action: DENY
  rules:
    - {}
