apiVersion: v2
name: my-airflow-chart
description: A wrapper chart that installs the official Airflow Helm Chart
type: application
version: 0.2.0
appVersion: "2.9.3"

dependencies:
  - name: airflow
    version: "1.18.0"
    repository: "https://airflow.apache.org"
