apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

helmCharts:
  - name: airflow
    repo: https://charts.bitnami.com/bitnami
    version: 16.8.3 # latest stable from Bitnami
    releaseName: airflow
    valuesInline:
      executor: LocalExecutor
      airflow:
        fernetKey:
          valueFrom:
            secretKeyRef:
              name: airflow
              key: fernet
        secretKey:
          valueFrom:
            secretKeyRef:
              name: airflow
              key: secretKey
      webserver:
        defaultUser:
          enabled: true
          username: admin
          password: admin
      postgresql:
        enabled: true
        postgresqlDatabase: airflow
        postgresqlUsername: airflow
        postgresqlPassword: airflow
      redis:
        enabled: false
      scheduler:
        image:
          tag: latest
      web:
        image:
          tag: latest
      worker:
        image:
          tag: latest
