apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

helmCharts:
  - name: airflow
    repo: https://airflow.apache.org
    version: 1.18.0 # pick a stable release
    releaseName: airflow
    valuesInline:
      executor: LocalExecutor
      airflow:
        fernetKey:
          valueFrom:
            secretKeyRef:
              name: airflow
              key: fernet
        secretKey:
          valueFrom:
            secretKeyRef:
              name: airflow
              key: secretKey
      webserver:
        defaultUser:
          enabled: true
          username: admin
          password: admin
      postgresql:
        enabled: true
        postgresqlDatabase: airflow
        postgresqlUsername: airflow
        postgresqlPassword: airflow
      redis:
        enabled: false
      createUserJob:
        useHelmHooks: false
        applyCustomEnv: false
      migrateDatabaseJob:
        useHelmHooks: false
        applyCustomEnv: false
