resources:
  - http.yaml

helmCharts:
  - name: airflow
    repo: https://charts.bitnami.com/bitnami
    version: 13.0.4
    releaseName: airflow
    valuesInline:
      executor: LocalExecutor
      airflow:
        fernetKey: "YOUR_FERNET_KEY"
        secretKey: "YOUR_SECRET_KEY"
      webserver:
        defaultUser:
          enabled: true
          username: admin
          password: admin
      postgresql:
        enabled: true
        auth:
          postgresPassword: postgres
      redis:
        enabled: false
