helmCharts:
  - name: airflow
    repo: https://airflow.apache.org
    version: 1.18.0
    releaseName: airflow
    valuesInline:
      executor: LocalExecutor
      airflow:
        fernetKey:
          valueFrom:
            secretKeyRef:
              name: airflow
              key: fernet
        secretKey:
          valueFrom:
            secretKeyRef:
              name: airflow
              key: secretKey
      webserver:
        defaultUser:
          enabled: true
          username: admin
          password: admin
      postgresql:
        enabled: true
      redis:
        enabled: false
      migrateDatabaseJob:
        useHelmHooks: true
        applyCustomEnv: false
