helmCharts:
  - name: airflow
    repo: https://airflow.apache.org
    version: 1.18.0
    releaseName: airflow
    valuesInline:
      executor: LocalExecutor
      airflow:
        fernetKey:
          valueFrom:
            secretKeyRef:
              name: airflow
              key: fernet
        secretKey:
          valueFrom:
            secretKeyRef:
              name: airflow
              key: secretKey
      webserver:
        defaultUser:
          enabled: true
          username: admin
          password: admin
      postgresql:
        enabled: true
        auth:
          postgresPassword:
            valueFrom:
              secretKeyRef:
                name: airflow
                key: postgres-password
          username: airflow
          password:
            valueFrom:
              secretKeyRef:
                name: airflow
                key: airflow-db-password
        postgresqlDatabase: airflow
      redis:
        enabled: false
      createUserJob:
        useHelmHooks: false
        applyCustomEnv: false
      migrateDatabaseJob:
        useHelmHooks: false
        applyCustomEnv: false
