config:
  AIRFLOW__WEBSERVER__BASE_URL: "https://airflow.bergtobias.com"
  AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
airflow:
  airflow:
    extraEnvFrom:
      - secretRef:
          name: github-airflow-oauth
  web:
    webserverConfig:
      enabled: true
      stringOverride: |
        import os
        from flask_appbuilder.security.manager import AUTH_OAUTH

        AUTH_TYPE = AUTH_OAUTH
        AUTH_USER_REGISTRATION = True
        AUTH_USER_REGISTRATION_ROLE = "User"

        OAUTH_PROVIDERS = [
            {
                "name": "github",
                "icon": "fa-github",
                "token_key": "access_token",
                "remote_app": {
                    "client_id": "Ov23liecQJZoDZHyAW3C",
                    "client_secret": "456a5f419c8b99af0056274981ca9e008f55439f",
                    "api_base_url": "https://api.github.com/",
                    "client_kwargs": {"scope": "read:user,user:email,read:org"},
                    "access_token_url": "https://github.com/login/oauth/access_token",
                    "authorize_url": "https://github.com/login/oauth/authorize",
                    "request_token_url": None,
                },
            }
        ]
