# Use existing secret for Airflow keys
airflow:
  existingSecret: "airflow"
# Disable Redis completely
redis:
  enabled: false
# PostgreSQL (internal, optional)
postgresql:
  enabled: true
  postgresqlPassword: "YOUR_DB_PASSWORD" # or use existing secret
# Use Bitnami default images (v3.0.5)
image:
  repository: bitnami/airflow
  tag: 3.0.5-debian-12-r0
  pullPolicy: IfNotPresent
# Set images for scheduler, worker, and web explicitly

# Optional: Persist logs and configs
persistence:
  enabled: true
  storageClass: standard
  accessMode: ReadWriteOnce
  size: 5Gi
# Extra environment variables
extraEnvVars: []
