airflow:
  airflow:
    image:
      repository: apache/airflow
      tag: "2.9.3" # or latest stable 2.9.x
    executor: "KubernetesExecutor"
    config:
      AIRFLOW__WEBSERVER__BASE_URL: "https://airflow.bergtobias.com"
      AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
      AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
      AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
      AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE: "True"
      AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "False" # since you use gitSync

    extraEnv:
      - name: GITHUB_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: github-airflow-oauth
            key: client-id
      - name: GITHUB_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: github-airflow-oauth
            key: client-secret

  dags:
    gitSync:
      enabled: true
      repo: https://github.com/vercevo/dags
      branch: main
      rev: HEAD
      depth: 1
      subPath: ""
      wait: 60

  web:
    replicas: 1
    webserverConfig:
      enabled: true
      stringOverride: |-
        import os
        import requests
        import logging
        from airflow.providers.fab.auth_manager.security_manager.override import FabAirflowSecurityManagerOverride
        from flask_appbuilder.security.manager import AUTH_OAUTH

        log = logging.getLogger(__name__)

        AUTH_TYPE = AUTH_OAUTH
        AUTH_USER_REGISTRATION = True
        AUTH_ROLES_SYNC_AT_LOGIN = True
        AUTH_USER_REGISTRATION_ROLE = "Viewer"

        OAUTH_PROVIDERS = [
            {
                "name": "github",
                "icon": "fa-github",
                "token_key": "access_token",
                "remote_app": {
                    "client_id": os.getenv("GITHUB_CLIENT_ID"),
                    "client_secret": os.getenv("GITHUB_CLIENT_SECRET"),
                    "api_base_url": "https://api.github.com/",
                    "client_kwargs": {"scope": "read:user,user:email,read:org"},
                    "access_token_url": "https://github.com/login/oauth/access_token",
                    "authorize_url": "https://github.com/login/oauth/authorize",
                    "request_token_url": None,
                },
            }
        ]

        class GithubTeamSecurityManager(FabAirflowSecurityManagerOverride):
            def get_oauth_user_info(self, provider, resp):
                if provider != "github":
                    return super().get_oauth_user_info(provider, resp)

                token = resp.json().get("access_token")
                if not token:
                    raise Exception("No GitHub OAuth token returned")

                headers = {"Authorization": f"token {token}"}

                # Fetch user + teams
                me = requests.get("https://api.github.com/user", headers=headers).json()
                teams = requests.get("https://api.github.com/user/teams", headers=headers).json()

                log.info("=== DEBUG: GitHub login ===")
                log.info("User: %s", me)
                log.info("Teams: %s", teams)
                log.info("===========================")

                # Check membership
                role_keys = []
                for team in teams:
                    org = team.get("organization", {}).get("login", "").lower()
                    slug = team.get("slug", "").lower()
                    if org == "vercevo" and slug == "eggmans":
                        role_keys.append("Admin")

                if not role_keys:
                    raise Exception(f"Access denied: {me.get('login')} not in vercevo:eggmans")

                return {
                    "username": f"github_{me.get('login')}",
                    "email": me.get("email") or f"{me.get('login')}@email.notfound",
                    "first_name": me.get("name") or me.get("login"),
                    "last_name": "",
                    "role_keys": role_keys,
                }

        SECURITY_MANAGER_CLASS = GithubTeamSecurityManager

  redis:
    ## if the `stable/redis` chart is used
    enabled: false
  flower:
    ## if the airflow flower UI should be deployed
    enabled: false
  workers:
    ## if the airflow workers StatefulSet should be deployed
    enabled: false
