airflow:
  executor: "KubernetesExecutor"
  migrateDatabaseJob:
    useHelmHooks: false
  createUserJob:
    useHelmHooks: false

  env:
    - name: AIRFLOW__WEBSERVER__BASE_URL
      value: "https://airflow.bergtobias.com"
    - name: AIRFLOW__APISERVER__BASE_URL
      value: "https://airflow.bergtobias.com"
  secret:
    - envName: GITHUB_CLIENT_ID
      secretName: airflow-secret
      secretKey: github-id
    - envName: GITHUB_CLIENT_SECRET
      secretName: airflow-secret
      secretKey: github-secret

  fernetKey: fernet-key
  fernetKeySecretName: airflow-secret

  apiServer:
    extraVolumes:
      - name: webserver-config
        configMap:
          name: airflow-webserver
    extraVolumeMounts:
      - name: webserver-config
        mountPath: /opt/airflow/webserver_config.py
        subPath: webserver_config.py
        readOnly: true
