airflow:
  executor: "KubernetesExecutor"
  migrateDatabaseJob:
    useHelmHooks: false
  createUserJob:
    useHelmHooks: false

  secret:
    - envName: GITHUB_CLIENT_ID
      secretName: airflow-secret
      secretKey: github-id
    - envName: GITHUB_CLIENT_SECRET
      secretName: airflow-secret
      secretKey: github-secret

  fernetKey: fernet-key
  fernetKeySecretName: airflow-secret

  dags:
    persistence:
      enabled: false
    gitSync:
      enabled: true
      repo: "https://github.com/vercevo/dags.git"
      branch: main
      depth: 1
      subPath: ""

  apiServer:
    extraVolumes:
      - name: webserver-config
        configMap:
          name: airflow-webserver
    extraVolumeMounts:
      - name: webserver-config
        mountPath: /opt/airflow/webserver_config.py
        subPath: webserver_config.py
        readOnly: true
