airflow:
  executor: "KubernetesExecutor"
  migrateDatabaseJob:
    useHelmHooks: false
  createUserJob:
    useHelmHooks: false
  secret:
    - envName: GITHUB_CLIENT_ID
      secretName: github-airflow-oauth
      secretKey: client-id
    - envName: GITHUB_CLIENT_SECRET
      secretName: github-airflow-oauth
      secretKey: client-secret
