apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openmetadata-dependencies-dags
  namespace: openmetadata
  labels:
    app: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
