apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name }}-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.name }}
  source:
    repoURL: https://github.com/vercevo/platform-infra
    targetRevision: main
    path: charts/namespace-bootstrap-chart
    helm:
      values: |
        namespace: ${{ values.name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
