apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd # Ensure this matches your ArgoCD namespace
spec:
  project: default # Change this if you use a different ArgoCD project
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: "0.18.1" # Or a specific version like "0.9.15"
    helm:
      values: |
        installCRDs: true  # Optional: if you want to install CRDs automatically
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets # Change if you want to install into a different namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Automatically create namespace if it doesn’t exist
