apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-system-with-namespace
  title: Create Backstage System with Kubernetes Namespace
  description: Creates a new Backstage System entity and Kubernetes Namespace by opening a PR in your GitOps repo.
spec:
  owner: group:default/your-group
  type: service
  parameters:
    title: System Information
    type: object
    required:
      - name
      - description
      - owner
    properties:
      name:
        type: string
        title: System Name
        description: Unique system name (lowercase, no spaces)
      description:
        type: string
        title: System Description
      owner:
        type: string
        title: Owner (Backstage user or group)
  steps:
    - id: generate-namespace
      name: Generate Namespace Manifest
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
