apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-system-with-namespace
  title: Create Backstage System with Kubernetes Namespace
  description: Creates a new Backstage System entity and Kubernetes Namespace by opening a PR in your GitOps repo.
spec:
  owner: group:default/your-group
  type: service

  parameters:
    title: System Information
    type: object
    required:
      - name
      - description
      - owner
    properties:
      name:
        type: string
        title: System Name
        description: Unique system name (lowercase, no spaces)

      description:
        type: string
        title: System Description

      owner:
        type: string
        title: Owning Team
        description: Select an existing team from the Backstage catalog
        ui:field: OwnerPicker
        ui:props:
          allowedKinds: [Group]

  steps:
    - id: generate-files
      name: Generate Manifests
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}

    - id: create-pr
      name: Create PR in platform-infra repo
      action: github:repo:push
      input:
        repoUrl: github.com?owner=vercevo&repo=platform-infra
        defaultBranch: main
        gitCommitMessage: Create system ${{ parameters.name }}

    - id: register-system
      name: Register Backstage System
      action: catalog:register
      input:
        catalogInfoUrl: https://github.com/vercevo/platform-infra/blob/main/systems/${{ parameters.name }}.yaml
