apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: data-platform
spec:
  selector:
    app: minio
  ports:
    - name: s3
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: NodePort
