airflow:
  executor: "KubernetesExecutor"
  migrateDatabaseJob:
    useHelmHooks: false
  createUserJob:
    useHelmHooks: false
  secret:
    - envName: GITHUB_CLIENT_ID
      secretName: airflow-secret
      secretKey: client-id
    - envName: GITHUB_CLIENT_SECRET
      secretName: airflow-secret
      secretKey: client-secret
  fernetKey: fernet-key
  fernetKeySecretName: airflow-secret
