apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/vercevor/platform-infra
        revision: HEAD # or 'main'
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/vercevor/platform-infra
        targetRevision: HEAD
        path: '{{path}}' 
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}' 
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true