apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-system-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vercevo/platform-infra
    targetRevision: main
    path: namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: namespaces
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
