apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      labels:
        app: platform
    spec:
      containers:
        - name: platform
          imagePullPolicy: Always
          image: ghcr.io/vercevo/platform-web:main
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: VALHEIM_STATUS_ENDPOINT
              value: "https://valheim-server.valheim.svc.cluster.local/status.json"
          ports:
            - containerPort: 3000
