apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: platform
  namespace: platform
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
  hostnames:
    - "platform.bergtobias.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: platform
          port: 80
