helmCharts:
  - name: airflow
    repo: https://airflow.apache.org
    version: 1.18.0
    releaseName: airflow
    valuesInline:
      executor: LocalExecutor
      airflow:
        fernetKey:
          valueFrom:
            secretKeyRef:
              name: airflow
              key: fernet
        secretKey:
          valueFrom:
            secretKeyRef:
              name: airflow
              key: secretKey
      webserver:
        defaultUser:
          enabled: true
          username: admin
          password: admin
      postgresql:
        enabled: true
        auth:
          enablePostgresUser: true
          postgresPassword: secret
          username: test
          password: secret
        postgresqlDatabase: airflow
      connections:
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://test:secret@airflow-postgresql.airflow.svc.cluster.local:5432/airflow
      redis:
        enabled: false
