apiVersion: v1
kind: ResourceQuota
metadata:
  name: system-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    cpu: "2"
    memory: "4Gi"
    pods: "10"
    requests.cpu: "1"
    requests.memory: "2Gi"