apiVersion: v1
kind: ResourceQuota
metadata:
  name: system-quota
  namespace: {{ .Values.namespace | default "default" }}
spec:
  hard:
    cpu: {{ .Values.resourceQuota.limits.cpu | default "2" }}
    memory: {{ .Values.resourceQuota.limits.memory | default "4Gi" }}
    pods: {{ .Values.resourceQuota.limits.pods | default "10" }}
    requests.cpu: {{ index .Values.resourceQuota.limits "requests.cpu" | default "1" }}
    requests.memory: {{ index .Values.resourceQuota.limits "requests.memory" | default "2Gi" }}
