apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak
  namespace: keycloak
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
      sectionName: https # Bind to the HTTPS listener
  hostnames:
    - "keycloak.bergtobias.com"
  rules:
    - filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: X-Forwarded-Proto
                value: https
      backendRefs:
        - name: keycloak
          port: 80
