dex:
  replicaCount: 1
  rbac:
    create: true
    createClusterScoped: false
  ingress:
    enabled: true
    className: nginx
    annotations:
      ingress.kubernetes.io/proxy-body-size: 100M
      ingress.kubernetes.io/app-root: '/'
    hosts:
      - host: dex.bergtobias.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: dex-secret
        hosts:
          - dex.bergtobias.com
  serviceMonitor:
    enabled: false
