dex:
  replicaCount: 1
  rbac:
    create: true
    createClusterScoped: false
  ingress:
    enabled: true
    className: nginx
    annotations:
      ingress.kubernetes.io/proxy-body-size: 100M
      ingress.kubernetes.io/app-root: '/'
    hosts:
      - host: dex.bergtobias.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: dex-secret
        hosts:
          - dex.bergtobias.com
  serviceMonitor:
    enabled: false
  config:
    issuer: https://dex.bergtobias.com
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 5556
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Iv23liYT6ofML2cJDGIy
          clientSecret: ad5ca103d8ee1066f4b2dac714ebaa93f8eac52d ## will be replaced by the secret tempo now
          redirectURI: https://dex.bergtobias.com/callback
          orgs:
            - name: vercevo
  service:
    type: ClusterIP
    port: 5556
