apiVersion: batch/v1
kind: Job
metadata:
  name: create-extra-dbs
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: psql
          image: postgres:15
          env:
            - name: PGPASSWORD
              value: mypassword
          command:
            - sh
            - -c
            - |
              psql -h postgres.postgres.svc.cluster.local -U myuser -d mydb \
                -c "CREATE DATABASE openmetadata_db;"
              psql -h postgres.postgres.svc.cluster.local -U myuser -d mydb \
                -c "CREATE DATABASE airflow_db;"
