apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: default-ip-pool
spec:
  addresses:
    - 192.168.10.200-192.168.10.240 # Your IP range for LB assignment
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
  name: default-l2-advertisement
spec:
  ipAddressPools:
    - default-ip-pool
