namespace: my-system
users: []
groups: []
networkPolicy:
  enabled: true
  allowSameNamespaceIngress: true
resourceQuota:
  enabled: true
  limits:
    cpu: "4"
    memory: "8Gi"
    pods: "10"
    requests.cpu: "2"
    requests.memory: "4Gi"
apps:
  - repoUrl: https://github.com/example/app1
    revision: main
    path: charts/myapp
    type: helm
    helm:
      valuesFiles:
        - values.yaml
      parameters:
        - name: replicaCount
          value: "2"
  - repoUrl: https://github.com/example/app2
    revision: develop
    path: overlays/prod
    type: kustomize
