apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newcasts-namespace
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: newcasts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/vercevo/platform-infra
    targetRevision: HEAD
    path: charts/namespace-bootstrap-chart
    helm:
      values: |
        namespace: newcasts
        apps:
          - repoURL: https://github.com/bergtobias/homelab-infra
            revision: main
            path: apps/eggman
            type: kustomize

            
