apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newcasts-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: newcasts
  source:
    repoURL: https://github.com/vercevo/platform-infra
    targetRevision: main
    path: charts/namespace-bootstrap-chart
    helm:
      values: |
        namespace: newcasts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
