apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-security-manager
data:
  override.py: |
    from airflow.providers.fab.auth_manager.security_manager.override import FabAirflowSecurityManagerOverride

    TEAM_ID_ADMIN = "eggmans"
    TEAM_ID_VIEWER = "eggmans"

    def team_parser(team_payload: dict) -> list[int]:
        return [team["id"] for team in team_payload]

    class CustomSecurityManager(FabAirflowSecurityManagerOverride):
        def map_roles(self, team_ids: list[int]) -> list[str]:
            role_map = {
                TEAM_ID_ADMIN: "Admin",
                TEAM_ID_VIEWER: "Viewer",
            }
            roles = [role_map[tid] for tid in team_ids if tid in role_map]
            return roles or ["Public"]
