apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: airflow
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
  hostnames:
    - "airflow.bergtobias.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: airflow-web
          port: 8080
