apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
  hostnames:
    - "argocd.bergtobias.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/acme-challenge/
      backendRefs:
        - name: cm-acme-http-solver-xxx47 # Replace with your actual solver service name
          namespace: argocd
          port: 8089 # Default solver port
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argocd-server
          port: 80
