apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant
  namespace: smarthome
data:
  configuration.yaml: |
    default_config:

    mqtt:
      discovery: true
      broker: "mqtt"   # hostname or IP of your broker


    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16

    frontend:
      themes:
        default:
          primary-color: "#3498db"
          accent-color: "#e74c3c"

    automation: []

    script: {}

    scene: {}
