apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant
  namespace: smarthome
data:
  configuration.yaml: |
    default_config:



    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16

    frontend:
      themes:
        default:
          primary-color: "#3498db"
          accent-color: "#e74c3c"

    automation: !include automations.yaml

    script: {}

    scene: {}
