apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      initContainers:
        - name: copy-config
          image: busybox
          command:
            - sh
            - -c
            - cp /tmp/configmap/configuration.yaml /config/configuration.yaml
          volumeMounts:
            - name: config-pvc
              mountPath: /config
            - name: config-cm
              mountPath: /tmp/configmap
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:stable
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_RAWIO
                - NET_RAW
                - SYS_ADMIN
          ports:
            - containerPort: 8123
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: config-pvc
              mountPath: /config
            - name: usb
              mountPath: /dev/ttyUSB0
            - name: bluetooth
              mountPath: /dev/hci0
          env:
            - name: TZ
              value: Europe/Stockholm
      volumes:
        - name: config-pvc
          persistentVolumeClaim:
            claimName: homeassistant
        - name: config-cm
          configMap:
            name: homeassistant
        - name: usb
          hostPath:
            path: /dev/ttyUSB0
            type: CharDevice
        - name: bluetooth
          hostPath:
            path: /dev/hci0
            type: CharDevice
