apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      initContainers:
        - name: create-ha-files
          image: busybox
          command:
            [
              "sh",
              "-c",
              "touch /config/automations.yaml /config/scenes.yaml /config/scripts.yaml",
            ]
          volumeMounts:
            - name: config-pvc
              mountPath: /config
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:stable
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_RAWIO
                - NET_RAW
                - SYS_ADMIN
          ports:
            - containerPort: 8123
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: config-pvc
              mountPath: /config
            - name: config-cm
              mountPath: /config
            - name: dev
              mountPath: /dev
            - name: dbus-socket
              mountPath: /var/run/dbus/system_bus_socket
              readOnly: true
          env:
            - name: TZ
              value: Europe/Stockholm
      volumes:
        - name: config-pvc
          persistentVolumeClaim:
            claimName: homeassistant
        - name: config-cm
          configMap:
            name: homeassistant
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: dbus-socket
          hostPath:
            path: /var/run/dbus/system_bus_socket
            type: Socket
