apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homeassistant
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
  hostnames:
    - "ha.bergtobias.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: Host
                value: ha.bergtobias.com
      backendRefs:
        - name: homeassistant
          port: 8123
