apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant
  namespace: smarthome
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: local-path  # optional if local-path is default
