{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: system-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    cpu: {{ .Values.resourceQuota.limits.cpu }}
    memory: {{ .Values.resourceQuota.limits.memory }}
    pods: {{ .Values.resourceQuota.limits.pods }}
    requests.cpu: {{ .Values.resourceQuota.limits.requests.cpu }}
    requests.memory: {{ .Values.resourceQuota.limits.requests.memory }}
{{- end }}
