apiVersion: v2
name: openmetadata-stack
description: Full OpenMetadata stack with default dependencies
type: application
version: 0.1.0

dependencies:
  - name: openmetadata-dependencies
    version: 1.9.3
    repository: https://helm.open-metadata.org/

  - name: openmetadata
    version: 1.9.3
    repository: https://helm.open-metadata.org/
