apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmetadata
  namespace: openmetadata
  labels:
    app: openmetadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmetadata
  template:
    metadata:
      labels:
        app: openmetadata
    spec:
      containers:
        - name: server
          image: openmetadata/server:1.9.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8585
            - name: admin
              containerPort: 8586
          # Simple TCP probes on the admin port (8586) to avoid guessing health path
          readinessProbe:
            tcpSocket:
              port: 8586
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8586
            initialDelaySeconds: 60
            periodSeconds: 20
          env:
            # ===== Postgres =====
            - name: DB_DRIVER_CLASS
              value: org.postgresql.Driver
            - name: DB_SCHEME
              value: postgresql
            - name: DB_HOST
              value: postgres.postgres.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: myuser
            - name: DB_USER_PASSWORD
              value: mypassword
            - name: OM_DATABASE
              value: openmetadata_db

            # ===== Elasticsearch =====
            - name: ELASTICSEARCH_HOST
              value: elasticsearch.elastic.svc.cluster.local
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_SCHEME
              value: http
            - name: ELASTICSEARCH_USER
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              value: mypassword
            - name: JVM_OPTS
              value: "-Xms512m -Xmx1024m"
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
