apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openmetadata
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
  hostnames:
    - "openmeta.bergtobias.com" # change to your domain
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: openmetadata
          port: 80
