apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openmetadata

helmCharts:
  - name: openmetadata
    releaseName: openmetadata
    namespace: openmetadata
    version: 1.9.4
    repo: https://open-metadata.github.io/helm-charts
    valuesFile: values.yaml
