apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openmetadata

helmCharts:
  - name: openmetadata
    releaseName: openmetadata
    namespace: openmetadata
    repo: https://helm.open-metadata.org
    version: 1.9.3
    includeCRDs: true
    valuesInline:
      openmetadata:
        config:
          # === External Postgres ===
          database:
            enabled: true
            dbScheme: postgresql
            driverClass: org.postgresql.Driver
            host: postgres.postgres.svc.cluster.local
            port: 5432
            databaseName: openmetadata_db
            auth:
              username: myuser
              # Recommended: store password in a Secret and reference it:
              password:
                secretRef: om-db
                secretKey: password

          # === Elasticsearch ===
          elasticsearch:
            enabled: true
            searchType: elasticsearch # use "opensearch" if applicable
            host: elasticsearch.elastic.svc.cluster.local
            port: 9200
            scheme: http
            auth:
              enabled: true
              username: elastic
              password:
                secretRef: om-es
                secretKey: password

        # Pod resources for the OM server Deployment
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
