apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openmetadata

helmCharts:
  - name: openmetadata
    releaseName: openmetadata
    namespace: openmetadata
    version: 1.9.3
    repo: https://helm.open-metadata.org
    valuesFile: values.yaml
