apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openmetadata

helmCharts:
  - name: openmetadata
    releaseName: openmetadata
    namespace: openmetadata
    repo: https://helm.open-metadata.org
    version: 1.9.3
    valuesFile: values.yaml
    includeCRDs: true
