openmetadata:
  config:
    database:
      enabled: true
      dbScheme: postgresql
      driverClass: org.postgresql.Driver
      host: postgres.postgres.svc.cluster.local # matches your Service
      port: 5432
      databaseName: openmetadata_dbs
      auth:
        username: myuser
        password:
          secretRef: openmetadata-postgresql-secrets
          secretKey: openmetadata-postgresql-password
