# Disable the bundled dependency chart
dependencies:
  enabled: false

openmetadata:
  config:
    # --- Database: Postgres instead of MySQL ---
    database:
      enabled: true
      dbScheme: postgresql
      driverClass: org.postgresql.Driver
      host: postgres.postgres.svc.cluster.local
      port: 5432
      databaseName: openmetadata_db
      auth:
        username: myuser
    # Elasticsearch connection
    elasticsearch:
      enabled: true
      searchType: elasticsearch
      host: elasticsearch.elastic.svc.cluster.local
      port: 9200
      scheme: http
      auth:
        enabled: true
        username: elastic
  # Put passwords here if you don’t want Secrets yet
  extraEnvs:
    - name: DB_USER_PASSWORD
      value: mypassword
    - name: ELASTICSEARCH_PASSWORD
      value: mypassword
