# === Dependency chart overrides ===
openmetadata-dependencies:
  mysql:
    enabled: false # disable MySQL
  elasticsearch:
    enabled: true
    host: elasticsearch.elastic.svc.cluster.local
    port: 9200
    scheme: http
    auth:
      enabled: true
      username: elastic
      password: mypassword
  minio:
    enabled: true
    host: minio.minio.svc.cluster.local
    port: 9000
    bucket: openmetadata
    accessKey: myuser
    secretKey: mypassword
    region: us-east-1
    forcePathStyle: true
  airflow:
    enabled: false # skip Airflow for now

# === Core OpenMetadata server ===
openmetadata:
  config:
    database:
      enabled: true
      dbScheme: postgresql
      driverClass: org.postgresql.Driver
      host: postgres.postgres.svc.cluster.local
      port: 5432
      databaseName: openmetadata_db
      auth:
        username: myuser
        password:
          secretRef: openmetadata-db-secret
          secretKey: openmetadata-postgresql-password

    elasticsearch:
      enabled: true
      searchType: elasticsearch
      host: elasticsearch.elastic.svc.cluster.local
      port: 9200
      scheme: http
      auth:
        enabled: true
        username: elastic
        password:
          secretRef: openmetadata-es-secret
          secretKey: openmetadata-elasticsearch-password

    airflow:
      enabled: false
    pipelineServiceClientConfig:
      enabled: false

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
