openmetadata:
  config:
    database:
      host: <postgresql_endpoint>
      port: 5432
      driverClass: org.postgresql.Driver
      dbScheme: postgresql
      dbUseSSL: true
      databaseName: <openmetadata_database_name>
      auth:
        username: <database_login_user>
        password:
          secretRef: openmetadata-postgresql-secrets
          secretKey: openmetadata-postgresql-password

    # === Elasticsearch ===
    elasticsearch:
      enabled: true
      searchType: elasticsearch
      host: elasticsearch.elastic.svc.cluster.local
      port: 9200
      scheme: http
      auth:
        enabled: true
        username: elastic
        password:
          secretRef: openmetadata-elasticsearch-secrets
          secretKey: openmetadata-elasticsearch-password

    # === Disable Airflow completely ===
    airflow:
      enabled: false
    pipelineServiceClientConfig:
      enabled: false

  # Resources (as you always want in your Deployments)
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
