openmetadata:
  # --- no built-in deps, no Airflow ---
  config:
    airflow:
      enabled: false
    pipelineServiceClientConfig:
      enabled: false

    # --- use your external Postgres (NOT MySQL) ---
    database:
      enabled: true
      dbScheme: postgresql
      driverClass: org.postgresql.Driver
      host: postgres.postgres.svc.cluster.local # change if different
      port: 5432
      databaseName: openmetadata_db
      auth:
        username: myuser
        password:
          secretRef: openmetadata-secrets # single secret for all creds
          secretKey: db-password

    # --- use your external Elasticsearch ---
    elasticsearch:
      enabled: true
      searchType: elasticsearch # or "opensearch" if that’s what you run
      host: elasticsearch.elastic.svc.cluster.local
      port: 9200
      scheme: http
      auth:
        enabled: true
        username: elastic
        password:
          secretRef: openmetadata-secrets
          secretKey: es-password

  # Pod sizing (you asked to always include resources in deployments)
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

  # OPTIONAL: enable Ingress if you want HTTP right away (nginx example)
  # ingress:
  #   enabled: true
  #   className: nginx
  #   hosts:
  #     - host: openmetadata.example.com
  #       paths:
  #         - path: /
  #           pathType: Prefix
