openmetadata-dependencies:
  airflow:
    scheduler:
      resources:
        requests:
          memory: 256Mi
        limits:
          memory: 512Mi
    triggerer:
      resources:
        requests:
          memory: 256Mi
        limits:
          memory: 512Mi
    web:
      resources:
        requests:
          memory: 256Mi
        limits:
          memory: 512Mi
    workers:
      resources:
        requests:
          memory: 256Mi
        limits:
          memory: 512Mi
    extraVolumeMounts:
      - mountPath: /airflow-logs
        name: efs-airflow-logs
      - mountPath: /airflow-dags/dags
        name: efs-airflow-dags
    extraVolumes:
      - name: efs-airflow-logs
        persistentVolumeClaim:
          claimName: openmetadata-dependencies-logs-pvc
      - name: efs-airflow-dags
        persistentVolumeClaim:
          claimName: openmetadata-dependencies-dags-pvc
    config:
      AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS: "/airflow-dags/dags"
  dags:
    path: /airflow-dags/dags
    persistence:
      enabled: false
  logs:
    path: /airflow-logs
    persistence:
      enabled: false
  mysql:
    primary:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
opensearch:
  enabled: true
  fullnameOverride: opensearch
  master:
    replicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  data:
    replicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
