openmetadata:
  # --- turn OFF Airflow to avoid airflow-secrets ---
  config:
    airflow:
      enabled: false
    pipelineServiceClientConfig:
      enabled: false

    # --- use external Postgres (no mysql-secrets) ---
    database:
      enabled: true
      dbScheme: postgresql
      driverClass: org.postgresql.Driver
      host: postgres.postgres.svc.cluster.local
      port: 5432
      databaseName: openmetadata_db
      auth:
        username: myuser
        # IMPORTANT: clear secretRef/secretKey so Helm doesn't template mysql-secrets
        password:
          secretRef: "openmetadata"
          secretKey: "db-password"

    # --- external Elasticsearch ---
    elasticsearch:
      enabled: true
      searchType: elasticsearch
      host: elasticsearch.elastic.svc.cluster.local
      port: 9200
      scheme: http
      auth:
        enabled: true
        username: elastic
        password:
          secretRef: "openmetadata"
          secretKey: "db-password"

  # optional pod sizing
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
