apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${{ values.name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ${{ values.name }} # name of resulting Kubernetes Secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ${{ values.name }}
