apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  labels:
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  selector:
    app: ${{ values.name }}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
