apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-bergtobias-com
  namespace: istio-system
spec:
  secretName: bergtobias-com-cert
  dnsNames:
    - "*.bergtobias.com"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
