apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-cert
spec:
  secretName: argocd-secret
  issuerRef:
    name: prod-issuer
    kind: Issuer
  commonName: "*.bergtobias.com"
  dnsNames:
    - "*.bergtobias.com"
