apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  addresses:
    - type: IPAddress
      value: "192.168.10.218"
  listeners:
    - name: http
      hostname: "*.bergtobias.com"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      hostname: "*.bergtobias.com"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: istio-ingressgateway-certs
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
