apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: istio-system
spec:
  acme:
    email: tobiaswillyberg@gmail.com
    server: http://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: tobiaswillyberg@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
