apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-lan-bergtobias-com
  namespace: istio-system
spec:
  secretName: lan-bergtobias-com-cert
  dnsNames:
    - "*.lan.bergtobias.com"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
