apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nest-service
  title: NestJS Microservice
  description: Creates a new NestJS app with GitOps manifests and registers it in Backstage
spec:
  owner: group:default/eggmans
  type: service

  parameters:
    title: Fill in some steps
    type: object
    required:
      - name
      - owner
      - system
      - description
    properties:
      name:
        title: Name
        type: string
        description: Unique name of the component
        ui:autofocus: true
        ui:options:
          rows: 5
      description:
        title: Description
        type: string
        description: A short description of the component
        ui:options:
          rows: 5
      owner:
        title: Owner
        type: string
        description: Owner of the component
        ui:field: OwnerPicker
        ui:options:
          catalogFilter:
            kind: Group
      system:
        title: System
        type: string
        description: The system this service belongs to
        ui:field: EntityPicker
        ui:options:
          catalogFilter:
            kind: System

  steps:
    - id: fetch-base
      name: Fetch NestJS boilerplate
      action: fetch:template
      input:
        url: ./content/app
        targetPath: .
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          description: ${{ parameters.description }}
          system: ${{ parameters.system }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=vercevo&repo=${{ parameters.name }}
        defaultBranch: main
        description: ${{ parameters.description }}
        gitCommitMessage: Add NestJS service ${{ parameters.name }} [skip ci]

    - id: register
      name: Register in Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
